app/models.py
from datetime import datetime

from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

from . import db, login_manager

class User(UserMixin, db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique = True)
    hash_pass = db.Column(db.String(255))
    blogs = db.relationship('Blog', backref = 'user', lazy = "dynamic")
    comments = db.relationship('Comment', backref = 'user', lazy = "dynamic")

    @property
    def password(self):
        raise AttributeError("You cannot read password attribute")

    @password.setter
    def password(self, pass_entry):
        self.hash_pass = generate_password_hash(pass_entry)

    def verify_password(self, pass_entry):
        return check_password_hash(self.hash_pass, pass_entry)

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self.id

    def __repr__(self):
        return f'User {self.username}::{self.id}'

class Blog(db.Model):
    __tablename__ = 'blogs'

    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String())
    content = db.Column(db.String())
    created_at = db.Column(db.DateTime, default = datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref = 'blog', lazy = "dynamic")

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self.id

    @staticmethod
    def get_user_blogs(user_id):
        return Blog.query.filter_by(user_id = user_id).all()

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer, primary_key= True)
    content = db.Column(db.String())
    blog_id = db.Column(db.Integer, db.ForeignKey('blogs.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))

    def save(self):
        db.session.add(self)
        db.session.commit()
        return self.id

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import Required

class NewBlogForm(FlaskForm):
    title = StringField('Title', validators=[Required()])
    content = TextAreaField('Content', validators=[Required()])
    submit = SubmitField('Submit')

class CommentForm(FlaskForm):
    comment = TextAreaField('Comment', validators=[Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_mail import Mail

from config import config_options

db = SQLAlchemy()
mail = Mail()

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

def create_app(config_name):
    app = Flask(__name__)

    # Loading Configuration Options
    app.config.from_object(config_options[config_name])

    # Initialize Extensions
    db.init_app(app)
    mail.init_app(app)
    login_manager.init_app(app)
    
    # Registering Blueprints
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint, url_prefix = "/authenticate")

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, errors

app/main/views.py
from flask import render_template, url_for, redirect, flash
from flask_login import current_user, login_required
import requests

from . import main
from .. import db
from ..models import User, Blog, Comment
from .forms import NewBlogForm, CommentForm
from ..email import mail_message

@main.route("/")
def index():
    all_blogs = Blog.query.order_by(db.desc(Blog.created_at)).limit(15).all()
    try:
        quote = requests.get('http://quotes.stormconsultancy.co.uk/random.json').json()['quote']
    except Exception:
        quote = ""
  
    return render_template("index.html", blogs = all_blogs, quote = quote)

@main.route("/blog/new", methods = ['GET', 'POST'])
@login_required
def new_blog():
    form = NewBlogForm()
    if form.validate_on_submit():
        email_list = []
        new_blog = Blog(title = form.title.data, content = form.content.data, user = current_user)
        new_blog_id = new_blog.save()

        all_users = User.query.all()
        for user in all_users:
            email_list.append(user.email)

        mail_message("New blog notification","email/welcome_user",user.email, user=user)
        return redirect(url_for('main.blog_content', blog_id = new_blog_id))

    return render_template("new_blog.html", form = form)

@main.route("/blog/view/<blog_id>", methods = ['GET', 'POST'])
@login_required
def blog_content(blog_id):
    curr_blog = Blog.query.filter_by(id = blog_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        new_comment = Comment(content = form.comment.data, user = current_user, blog = curr_blog)
        new_comment.save()
        return redirect(url_for('main.blog_content', blog_id = blog_id))

    comments = Comment.query.filter_by(blog = curr_blog).all()

    return render_template('blog.html', blog = curr_blog, form = form, comments = comments)

@main.route("/blogs")
def view_blogs():
    all_blogs = Blog.query.order_by(db.desc(Blog.created_at)).all()
    
    return render_template("blogs.html", blogs = all_blogs)

@main.route("/account")
@login_required
def profile():
    user_blogs = Blog.query.filter_by(user = current_user).all()
    return render_template('profile.html', user = current_user, blogs = user_blogs)

@main.route("/blog/delete/<blog_id>")
@login_required
def delete_blog(blog_id):
    to_delete = Blog.query.filter_by(user = current_user, id = blog_id).first()
    if to_delete:
        db.session.delete(to_delete)
        db.session.commit()
        flash("Blog deleted successfully")
        return render_template('delete_response.html')
    else:
        flash("Blog deletion failed")
        return render_template('delete_response.html')
    
@main.route("/blog/update/<blog_id>", methods = ['GET','POST'])
@login_required
def update_blog(blog_id):
    form = NewBlogForm()
    user_change_blog = Blog.query.filter_by(user = current_user, id = blog_id).first()

    if user_change_blog is None:
        return redirect(url_for('main.blog_content', blog_id = blog_id))

    if form.validate_on_submit():
        user_change_blog.title = form.title.data
        user_change_blog.content = form.content.data
        db.session.commit()

        return redirect(url_for('main.blog_content', blog_id = blog_id))

    form.content.data = user_change_blog.content
    return render_template('update.html', form = form, blog = user_change_blog)
    
@main.route("/comment/delete/<comment_id>", methods = ['GET','POST'])
@login_required
def delete_comment(comment_id):
    blog_owner = Comment.query.filter_by(id = comment_id).first().blog.user
    to_delete = Comment.query.filter_by(id = comment_id).first()

    if to_delete.blog.user == blog_owner:
        db.session.delete(to_delete)
        db.session.commit()
        flash("Comment deleted successfully")
        return redirect(url_for('main.review_blog', blog_id = to_delete.blog_id))
    else:
        flash("Comment deletion failed")
        return redirect(url_for('main.profile'))

@main.route("/blog/review/<blog_id>", methods = ['GET', 'POST'])
@login_required
def review_blog(blog_id):
    curr_blog = Blog.query.filter_by(user = current_user).first()
    user_blog_comments = Comment.query.filter_by(blog_id = blog_id).all()

    return render_template('review_blog.html', comments = user_blog_comments)

app/templates/base.html
<!DOCTYPE html>
  <html>
    <head>
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
      <title>Blog App</title>
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
      <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
      <link href="data:image/x-icon;base64,AAABAAEAEBAQAAEABAAoAQAAFgAAACgAAAAQAAAAIAAAAAEABAAAAAAAgAAAAAAAAAAAAAAAEAAAAAAAAAB88u4AR5GPAAAAAAB66+cAZMTBAHLb2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIiIiJFVSIiIiIiJFMAACIiIiJFAAAAAiIiIlAAAAAyIiIkAAAAMyIiIiUAAAAyIiIiUwAAAzIiIiJQAAAzIiIiIlAAADMiIiIiUAAAMyIiIiJQAAAzIiIiIlAzVVMiIiIiVEEzVSIiIiJUETMzMiIiIlEVMzMyIiIiNVMzMyIiL+HwAA/AcAAPgDAAD4AwAA8AcAAPAPAADgDwAA4B8AAOAfAADgHwAA4B8AAOAfAADgHwAA4A8AAOAPAADgHwAA" rel="icon" type="image/x-icon" />
    </head>
    <body>
      {% block navbar%}
          {% include 'navbar.html' %}
      {% endblock navbar%}

      {% block content%}

      {% endblock content%}
      
      {% block footer%}
        {% include 'footer.html'%}
      {% endblock %}

      {% block scripts%}
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
      <script src="{{ url_for('static', filename='js/script.js') }}"></script>
      {% endblock scripts%}
    </body>
  </html>

app/templates/blog.html
{% extends 'base.html' %}

{% block content %}

<div class = "valign-wrapper">
<div class = "container">
    <div class="row">
    <div class="col l3 m3 s12"></div>
    <div class="col l6 m6 s12">
    <br>
    <h1>{{blog.title}}</h1>
    <p class="grey-text">By {{blog.user.username}}</p>
    <p>{{blog.content}}</p>
    <br><hr><br><br>

    {% if comments %}
    {% for comment in comments %}
    <div class = "card-panel">
        <p>{{ comment.content}}</p>
        <p class = "right-align grey-text"> By {{ comment.user.username }}</p>
    </div>
    {% endfor %}
    {% else %}
    <div class = "card-panel">
        <p>No commments on this blog</p>
    </div>
    {% endif %}
    <br>

    <form action = "{{ url_for('main.blog_content', blog_id = blog.id)}}" method="POST" autocomplete="off">
        <div class="">
        <div class = "input-field">
            {{ form.csrf_token(type_ = "hidden")}}
        </div>
        <div class = "input-field">
            {{ form.comment.label }}
            {{ form.comment(class_ = "materialize-textarea", placeholder = "Comment")}}
        </div>
        <div class = "input-field">
            {{ form.submit(class_ = "btn")}}
        </div>
    </div>       
    </form>
    </div>
    </div>
</div>
</div>
{% endblock content%}

app/templates/blogs.html
{% extends 'base.html' %}

{% block content %}
<div class = "container">
    <h3 class = "center">All Blogs</h3>
    <div class="row">
    {% for blog in blogs %}
    <div class="col s12 m4">
        <a href="{{url_for('main.blog_content', blog_id = blog.id)}}">
            <div class="card black-text darken-1 hoverable small">
                <br>
            <div class="card-content white-text">
            <span class="card-title black-text">{{blog.title}}</span>
            <p class = "black-text">{{blog.content | truncate(100)}}</p><br>
            <p class = "black-text">By {{blog.user.username}}</p>
            <p class = "grey-text">Created {{blog.created_at.strftime("%m-%d-%Y")}}</p>
            </div>
            <div class="card-action">
            <a href="{{url_for('main.blog_content', blog_id = blog.id)}}">View</a>
            </div>
        </div>
        </a>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

app/templates/delete_response.html
{% extends 'base.html' %}

{% block content %}
<div class = "valign-wrapper ba-screen-full">
    <div class = "container">
    <div class="row">
    <div class="col l3 m3 s12"></div>
    <div class="col l6 m6 s12">
        {% for message in get_flashed_messages() %}
            <div class="card-panel red">
            <span class = "white-text">{{ message }}</span>
            </div>
        {% endfor %}
    </div>
    </div>
    </div>
</div>
{% endblock content %}

app/templates/footer.html
<footer class="page-footer ba-footer">
    <div class="container">
      <div class="row">
        <div class="col l8 m6 s12">
          <h5 class="white-text">Blog App</h5>
          <p class="white-text">We have blogs.</p>
        </div>
        <div class="col l4 s12">
          <h5 class="white-text">Navigation</h5>
          <ul>
            <li><a class="white-text" href="/">Home</a></li>
            <li><a class="white-text" href="/blogs">Blogs</a></li>
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div>
        <h4>Subscribe to fun blog
          <button>Sign up!</button>
        </h4>
      </div>
      <div class="container">
      © 2019 Copyright: Fun blog.com
      </div>
    </div>
  </footer>

app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="valign-wrapper ba-jumbotron">
    <div class = "container center-align">
        <h2>The Blog App</h2>
        <h5 class = "grey-text">Read new Content</h5>
        <a class="waves-effect waves-light btn-large" href = "{{url_for('main.new_blog')}}">TRY IT NOW</a>
    </div>
</div>
<div class = "container">
    <h3 class = "center">Latest Blogs</h3>
    <p class = "center">{{quote}}</p>
    <div class="row">
    {% for blog in blogs %}
    <div class="col s12 m4">
        <a href="{{url_for('main.blog_content', blog_id = blog.id)}}">
            <div class="card black-text darken-1 hoverable small">
                <br>
            <div class="card-content white-text">
            <span class="card-title black-text">{{blog.title}}</span>
            <p class = "black-text">{{blog.content | truncate(100)}}</p><br>
            <p class = "black-text">By {{blog.user.username}}</p>
            <p class = "grey-text">Created {{blog.created_at.strftime("%m-%d-%Y")}}</p>
            </div>
            <div class="card-action">
            <a href="{{url_for('main.blog_content', blog_id = blog.id)}}">View</a>
            </div>
        </div>
        </a>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock content%}

app/templates/navbar.html
<nav>
    <div class="nav-wrapper white">
      <a href="/" class="brand-logo black-text ba-pl-1">Blog</a>
      <a href="" data-target="mobile-side" class="sidenav-trigger black-text"><i class="material-icons">menu</i></a>
      {% if current_user.is_authenticated %}
      <ul class="right">
        <li><a href="" class="black-text dropdown-trigger" data-target='account-drop'><i class="material-icons">account_circle</i></a></li>
      </ul>
      <ul id='account-drop' class='dropdown-content'>
        <li><a href="/account">Account</a></li>
        <li><a href="{{ url_for('auth.logout')}}">Logout</a></li>
      </ul>
      {% else %}
        <a href="{{url_for('auth.login')}}" class = "right black-text">Sign in</a>
      {%endif%}
      <ul class="right hide-on-med-and-down">
        <li><a href="/" class = "black-text">Home</a></li>
        <li><a href="/blogs" class = "black-text">Blogs</a></li>
      </ul>
    </div>
  </nav>
  <ul class="sidenav" id="mobile-side">
    <li><a href="/" class = "black-text">Home</a></li>
    <li><a href="" class = "black-text">Blogs</a></li>
  </ul>

app/templates/new_blog.html
{% extends 'base.html' %}

{% block content %}
<div class = "valign-wrapper ba-screen-full">
    <div class = "container">
    <div class="row">
    <div class="col l3 m3 s12"></div>
    <div class="col l6 m6 s12">
        {% for message in get_flashed_messages() %}
        <div class="card-panel red">
        <span class = "white-text">{{ message }}</span>
        </div>
    {% endfor %}<br>
    <form action = "{{ url_for('main.new_blog')}}" method="POST" autocomplete="off">
        <div class="">
        <div class = "input-field">
            {{ form.csrf_token(type_ = "hidden")}}
        </div>
        <div class = "input-field">
            {{ form.title.label }}
            {{ form.title(class_ = "validate", placeholder = "Title")}}
        </div>
        <div class = "input-field">
            {{ form.content.label }}
            {{ form.content(class_ = "materialize-textarea")}}
        </div> 
        
        <div class = "input-field">
            {{ form.submit(class_ = "btn")}}
        </div>
    </div>       
    </form>
    </div>
    </div>
    </div>
</div>
{% endblock content%}

app/templates/profile.html
{% extends 'base.html' %}

{% block content %}
<div class="valign-wrapper ba-jumbotron">
    <div class = "container center-align">
        <h4 class = "">Profile</h4>
        <p>{{user.username}}</p>
        <p>{{user.email}}</p>
        <a class="waves-effect waves-light btn-large" href = "{{url_for('main.new_blog')}}">NEW BLOG</a>
    </div>
</div>
<div class = "container">
    <h3 class = "center">Your Blogs</h3>
    <div class="row">
    {% for blog in blogs %}
    <div class="col s12 m4">
        <a href="{{url_for('main.blog_content', blog_id = blog.id)}}">
            <div class="card black-text darken-1 hoverable small">
                <br>
            <div class="card-content white-text">
            <span class="card-title black-text">{{blog.title}}</span>
            <p class = "black-text">{{blog.content | truncate(100)}}</p><br>
            <p class = "black-text">By {{blog.user.username}}</p>
            <p class = "grey-text">Created {{blog.created_at.strftime("%m-%d-%Y")}}</p>
            </div>
            <div class="card-action">
            <a href="{{url_for('main.blog_content', blog_id = blog.id)}}">VIEW</a>
            <a href="{{url_for('main.update_blog', blog_id = blog.id)}}">UPDATE</a>
            <a href="{{url_for('main.review_blog', blog_id = blog.id)}}">REVIEW</a>
            <a class = "red-text" href="{{url_for('main.delete_blog', blog_id = blog.id)}}">DELETE</a>
            </div>
        </div>
        </a>
    </div>
    {% endfor %}
    </div>
</div>
{% endblock content %}

app/templates/review_blog.html
{% extends 'base.html' %}

{% block content %}
<div class = "ba-screen-full">
<div class = "container">
    <div class="row">
    <div class="col l3 m3 s12"></div>
    <div class="col l6 m6 s12">
    <h3>Comments</h3>
    <p>You can moderate comments on your blog</p>
    {% for message in get_flashed_messages() %}
        <div class="card-panel red">
        <span class = "white-text">{{ message }}</span>
        </div>
    {% endfor %}<br>
    {% if comments %}
    {% for comment in comments %}
    <div class = "card-panel">
        <p>{{ comment.content}}</p>
        <p class = "right-align grey-text"> By {{ comment.user.username }}</p>
        <a class="waves-effect waves-light btn-small red" href = "{{url_for('main.delete_comment', comment_id = comment.id)}}"><i class="material-icons left">delete</i>button</a>
    </div>
    {% endfor %}
    {% else %}
    <div class = "card-panel">
        <p>No commments on this blog</p>
    </div>
    {% endif %}
    <br>
    </div>
    </div>
</div>
</div>
{% endblock content %}

app/templates/update.html
{% extends 'base.html' %}

{% block content %}
<div class = "valign-wrapper ba-screen-full">
    <div class = "container">
    <div class="row">
    <div class="col l3 m3 s12"></div>
    <div class="col l6 m6 s12">
        {% for message in get_flashed_messages() %}
        <div class="card-panel red">
        <span class = "white-text">{{ message }}</span>
        </div>
    {% endfor %}<br>
    <form action = "{{ url_for('main.update_blog', blog_id = blog.id)}}" method="POST" autocomplete="off">
        <div class="">
        <div class = "input-field">
            {{ form.csrf_token(type_ = "hidden")}}
        </div>
        <div class = "input-field">
            {{ form.title.label }}
            {{ form.title(class_ = "validate", placeholder = "Title", value=blog.title)}}
        </div>
        <div class = "input-field">
            {{ form.content.label }}
            {{ form.content(class_ = "materialize-textarea", data=blog.content)}}
        </div> 
        
        <div class = "input-field">
            {{ form.submit(class_ = "btn")}}
        </div>
    </div>       
    </form>
    </div>
    </div>
    </div>
</div>
{% endblock content%}